export default {
    demand_menu: [{
        key: -2,
        value_id: "app.requirements",
        icon: "../img/DM-1.png",
        count: 0
    }, {
        key: "0",
        value_id: "app.processing",
        icon: "../img/DM-2.png",
        count: 0
    }, {
        key: "1",
        value_id: "app.processed",
        icon: "../img/DM-3.png",
        count: 0
    }, ],
    favorite_menu: [{
        key: 1,
        value_id: "app.goods",
        icon: "../img/MF-1.png",
        url: "/page/mine/favorite/1",
        count: 0,
    }, {
        key: 2,
        value_id: "app.supplier",
        icon: "../img/MF-2.png",
        url: "/page/mine/favorite/2",
        count: 0,
    }, ],
    quotation_menu: [{
        key: "all",
        value_id: "quotation.all_quotation",
        icon: "../img/Q-1.png",
        url: "/page/mine/quotation-list"
    }, ],
    management_menu: [{
        key: "all",
        value_id: "order.status.all",
        icon: "../img/PM-1.png",
        url: "/page/mine/agent-product"
    }, {
        key: "pay",
        value_id: "app.proval",
        icon: "../img/PM-2.png",
        url: "/page/mine/agent-product"
    }, {
        key: "send",
        value_id: "app.provaling",
        icon: "../img/PM-3.png",
        url: "/page/mine/agent-product"
    }, {
        key: "receive",
        value_id: "app.not.provaled",
        icon: "../img/PM-4.png",
        url: "/page/mine/agent-product"
    }, {
        key: "all",
        value_id: "app.not.review",
        icon: "../img/PM-5.png",
        url: "/page/mine/agent-product"
    }, ]
}