export default {
    demand_menu: [{
        key: -2,
        value_id: "app.requirements",
        icon: "../img/DM-1.png",
        count: 0,
        url: "page/mine/requirement"
    }, {
        key: "0",
        value_id: "app.processing",
        icon: "../img/DM-2.png",
        count: 0,
        url: "page/mine/requirement"
    }, {
        key: "1",
        value_id: "app.processed",
        icon: "../img/DM-3.png",
        count: 0,
        url: "page/mine/requirement"
    }, ],
    favorite_menu: [{
        key: 1,
        value_id: "app.goods",
        icon: "../img/MF-1.png",
        url: "/page/mine/favorite/1",
        count: 0,
    }, {
        key: 2,
        value_id: "app.supplier",
        icon: "../img/MF-2.png",
        url: "/page/mine/favorite/2",
        count: 0,
    }, ],
    quotation_menu: [{
        key: "all",
        value_id: "quotation.all_quotation",
        icon: "../img/Q-1.png",
        url: "/page/mine/quotation-list"
    }, ],
    management_menu: [{
        value: 0,
        value_id: "mine.product.status.all",
        key: "total",
        icon: "../img/PM-1.png",
        url: "page/mine/agent-product"
    }, {
        value: 1,
        value_id: "mine.product.status.selling",
        key: "productUpCount",
        icon: "../img/PM-2.png",
        url: "page/mine/agent-product/1",
        count: 0,
    }, {
        value: 2,
        value_id: "mine.product.status.reviewimg",
        key: "productNoCount",
        icon: "../img/PM-3.png",
        url: "page/mine/agent-product/2",
        count: 0,
    }, {
        value: 3,
        value_id: "mine.product.status.unaudited",
        key: "productRefuseCount",
        icon: "../img/PM-4.png",
        url: "page/mine/agent-product/3",
        count: 0,
    }, {
        value: 4,
        value_id: "mine.product.status.unsold",
        key: "productDownCount",
        icon: "../img/PM-5.png",
        url: "page/mine/agent-product/4",
        count: 0,
    }, ]
}