export default {
	quot_title: [{
		id: 1,
		key: "quotation.commod",
		value: "commod"
	}, {
		id: 2,
		key: "quotation.brand",
		value: "commod"
	}, {
		id: 3,
		key: "quotation.specification",
		value: "commod"
	}, {
		id: 4,
		key: "quotation.art",
		value: "commod"
	}, {
		id: 5,
		key: "quotation.quantity",
		value: "commod"
	}, {
		id: 6,
		key: "quotation.agency.price",
		value: "commod"
	}, {
		id: 7,
		key: "quotation.platform.price",
		value: "commod"
	}, {
		id: 8,
		key: "quotation.shipping.charges",
		value: "commod"
	}, {
		id: 9,
		key: "quotation.profits",
		value: "commod"
	}, {
		id: 10,
		key: "quotation.offical",
		value: "commod"
	}, ],
	pay_mode: [{
		id: 0,
		key: "cart.pay.cash",
		value: "现金"
	}, {
		id: 1,
		key: "cart.pay.blank",
		value: "银行"
	}, {
		id: 2,
		key: "cart.pay.check",
		value: "支票"
	}, {
		id: 3,
		key: "cart.pay.other",
		value: "其他"
	}, ],
	invoice_type: [{
		id: 0,
		key: "special.vat.invoice",
		value: "增值锐专用发票"
	}, {
		id: 0,
		key: "vat.invoice",
		value: "增值锐发票"
	}, {
		id: 0,
		key: "ordinary.invoice",
		value: "普通发票"
	}, ]
}