export default {
	quot_title: [{
		id: 1,
		key: "quotation.logo",
		value: "logo"
	}, {
		id: 2,
		key: "app.brand",
		value: "brand"
	}, {
		id: 3,
		key: "mine.product.param",
		value: "specification"
	}, {
		id: 4,
		key: "quotation.platform.price",
		value: "plat_price"
	}, {
		id: 5,
		key: "quotation.agency.price",
		value: "agent_price"
	}],
	pay_mode: [{
		id: 0,
		key: "cart.pay.cash",
		value: "现金"
	}, {
		id: 1,
		key: "cart.pay.blank",
		value: "银行"
	}, {
		id: 2,
		key: "cart.pay.check",
		value: "支票"
	}, {
		id: 3,
		key: "cart.pay.other",
		value: "其他"
	}, ],
	invoice_type: [{
		id: 0,
		key: "special.vat.invoice",
		value: "增值锐专用发票"
	}, {
		id: 1,
		key: "vat.invoice",
		value: "增值锐发票"
	}, {
		id: 2,
		key: "ordinary.invoice",
		value: "普通发票"
	}, ]
}