/**
 * Created by WF on 2017/9/4.
 */
export default {
    menu: [{
        title: "app.about",
        list: [{
            key: 1000,
            title: "about.company.profile",
            url: "/page/"
        }, {
            key: 1001,
            title: "about.sartners.suppliers",
            url: "/page/"
        }, {
            key: 1002,
            title: "about.news",
            url: "/page/"
        }, ]
    }, {
        title: "about.user.guide",
        list: [{
            key: 2000,
            title: "about.tems.payment",
            url: "/page/"
        }, {
            key: 2001,
            title: "about.shipping.method",
            url: "/page/"
        }, {
            key: 2002,
            title: "app.feedback",
            url: "/page/"
        }, ]
    }, {
        title: "about.customer.service",
        list: [{
            key: 3000,
            title: "about.track.orders",
            url: "/page/"
        }, {
            key: 3001,
            title: "about.supplier.rating",
            url: "/page/"
        }, {
            key: 3002,
            title: "about.customer.protection",
            url: "/page/"
        }, ]
    }, {
        title: "about.contact.us",
        list: [{
            key: 3000,
            title: "about.feed.back",
            url: "/page/"
        }, {
            key: 3001,
            title: "about.how.supplier",
            url: "/page/"
        }, {
            key: 3002,
            title: "about.affiliate.program",
            url: "/page/"
        }, ]
    }, ]
}