export default {
	steps: [{
		key: 1,
		title: "mine.product.basic",
		default_message: "基础信息",
		icon: ""
	}, {
		key: 2,
		title: "mine.product.picture",
		default_message: "产品引导图",
		icon: ""
	}, {
		key: 3,
		title: "mine.product.attributes",
		default_message: "产品属性",
		icon: ""
	}, {
		key: 4,
		title: "mine.product.param",
		default_message: "产品规格",
		icon: ""
	}, {
		key: 5,
		title: "mine.product.introduction",
		default_message: "产品介绍",
		icon: ""
	}, {
		key: 6,
		title: "mine.product.packaging",
		default_message: "包装参数",
		icon: ""
	}, {
		key: 7,
		title: "mine.product.transport",
		default_message: "运输要求",
		icon: ""
	}],
	introduceType: [{
		key: 1,
		is_select: false,
		value: "product.edite.descrip",
	}, {
		key: 2,
		is_select: false,
		value: "product.edite.feature",
	}, {
		key: 3,
		is_select: false,
		value: "product.edite.paramter",
	}, {
		key: 4,
		is_select: false,
		value: "product.edite.attention",
	}, {
		key: 5,
		is_select: false,
		value: "product.edite.application",
	}, {
		key: 6,
		is_select: false,
		value: "product.edite.details",
	}, {
		key: 7,
		is_select: false,
		value: "product.edite.size",
	}, ],
	contentType: [{
		key: 1,
		value: "product.edite.picture",
	}, {
		key: 2,
		value: "product.edite.text",
	}],
	product_ins: [{
		key: "len",
		name: "mine.product.instruct_length",
		unit_key: "长度",
		type: 0,
		select_unit: 0,
		unit_name: "lengthUnit",
		unit_name_id: "lengthUnitId",
		unit: [],
	}, {
		key: "width",
		name: "mine.product.instruct_width",
		type: 0,
		select_unit: 0,
		unit_key: "长度",
		unit_name: "widthUnit",
		unit_name_id: "widthUnitId",
		unit: []
	}, {
		key: "height",
		name: "mine.product.instruct_height",
		type: 0,
		select_unit: 0,
		unit_key: "长度",
		unit_name: "heightUnit",
		unit_name_id: "heightUnitId",
		unit: []
	}, {
		key: "weight",
		name: "mine.product.instruct_Weight",
		type: 0,
		select_unit: 0,
		unit_key: "重量",
		unit_name: "weightUnit",
		unit_name_id: "weightUnitId",
		unit: []
	}, {
		key: "specInfo",
		name: "mine.product.instruct_pack",
		type: 1,
		select_unit: [],
		unit_key: "长度,重量,质量",
		unit_key_2: "包装规格",
		unit_name: ["specMeteringUnit", "specVolumeUnit"],
		unit_name_id: ["specMeteringUnitId", "specVolumeUnitId"],
		unit: []
	}, {
		key: "special",
		name: "mine.product.instruct_special",
		type: 2,
		select_unit: 0,
		unit_name_id: "types",
		unit_name: "typeNames",
		unit: [{
			key: 1,
			value: "易碎",
			name: "mine.product.special_fragile"
		}, {
			key: 2,
			value: "粉尘",
			name: "mine.product.special_dust"
		}, {
			key: 3,
			value: "液体",
			name: "mine.product.special_liquid"
		}, {
			key: 4,
			value: "腐蚀",
			name: "mine.product.special_corrosion"
		}]
	}, {
		key: "remark",
		name: "mine.product.instruct_other",
		type: 3,
	}],
	transport: [{
		key: 1,
		name: "超宽",
		value: "product.edite.transport.width"
	}, {
		key: 2,
		name: "超长",
		value: "product.edite.transport.length"
	}, {
		key: 3,
		name: "超高",
		value: "product.edite.transport.height"
	}]

}